#FROM php:5.6-apache
FROM php:7.0.33-apache
#FROM php:7.4-apache

RUN apt update
RUN apt upgrade -y
RUN apt install -y apt-utils \
 curl \
 iputils-ping \
 less \
 nano \
 netcat

ENTRYPOINT ["/bin/bash"]
