FROM centos:centos7.7.1908

RUN yum -y update
RUN yum -y install epel-release && \
 yum -y groupinstall "Development Tools" && \
 yum -y install \
  apr-devel \
  apr-util-devel \
  autoconf \
  bison \
  bison-devel \
  bzip2-devel \
  curl \
  curl-devel \
  gcc \
  gcc-c++ \
  gd* \
  gd-devel \
  httpd-devel \
  httpd-tools \
  less \
  libcurl-devel \
  libicu-devel \
  libidn* \
  libidn-devel \
  libjpeg-devel \
  libmcrypt* \
  libpng-devel \
  libssh2 \
  libssh2-devel \
  libtidy-devel \
  libtool-ltdl-devel \
  libxml2-devel \
  libxslt-devel \
  nano \
  net-snmp-devel \
  openldap-devel \
  openssl \
  openssl-devel \
  pcre-devel \
  readline-devel \
  tar \
  wget
RUN yum clean all

WORKDIR /
ENTRYPOINT ["bash"]
EXPOSE 80